/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author COLNGE
 */
public class INICIO extends javax.swing.JFrame {
    static Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form INICIO
     */
    public INICIO() {
        initComponents();
        mostrarDatos();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextMASCOTA = new javax.swing.JTextField();
        jTextRAZA = new javax.swing.JTextField();
        jTextEDAD = new javax.swing.JTextField();
        jTextDUEÑO = new javax.swing.JTextField();
        jTextCELULAR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BOTON_GUARDAR = new javax.swing.JToggleButton();
        BOTON_VER = new javax.swing.JToggleButton();
        BOTON_BORRAR = new javax.swing.JToggleButton();
        BOTON_MODIFICAR = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablamascotas = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MASCOTA");

        jLabel2.setText("RAZA");

        jLabel3.setText("EDAD");

        jLabel4.setText("DUEÑO");

        jLabel5.setText("CELULAR");

        BOTON_GUARDAR.setText("CREAR");
        BOTON_GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_GUARDARActionPerformed(evt);
            }
        });

        BOTON_VER.setText("VER");
        BOTON_VER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_VERActionPerformed(evt);
            }
        });

        BOTON_BORRAR.setText("BORRAR");
        BOTON_BORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_BORRARActionPerformed(evt);
            }
        });

        BOTON_MODIFICAR.setText("MODIFICAR");
        BOTON_MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_MODIFICARActionPerformed(evt);
            }
        });

        tablamascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mascota", "Raza", "Edad", "Dueño", "Celularl"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablamascotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextDUEÑO, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextEDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextCELULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextRAZA, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextMASCOTA, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BOTON_GUARDAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BOTON_VER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BOTON_BORRAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BOTON_MODIFICAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextMASCOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BOTON_GUARDAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextRAZA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BOTON_VER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BOTON_BORRAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDUEÑO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BOTON_MODIFICAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCELULAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTON_GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_GUARDARActionPerformed
        try {
    String sql = ("INSERT INTO mascota(mascota, raza, edad, dueño, celular)VALUES (?,?,?,?,?)");
          con= DriverManager.getConnection("jdbc:mysql://localhost:3306/mascota","colunge","12345678");
          pst = con.prepareStatement(sql);
          pst.setString(1,jTextMASCOTA.getText());
          pst.setString(2,jTextRAZA.getText());
          pst.setString(3,jTextEDAD.getText());
          pst.setString(4,jTextDUEÑO.getText());
          pst.setString(5,jTextCELULAR.getText());
          pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "Se registro perfectamente.");     
} 
catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo incertar los datos. Puede ser que el ID ya exista. Intenta mas tarde."); 
        }
        mostrarDatos();
    }//GEN-LAST:event_BOTON_GUARDARActionPerformed

    private void BOTON_VERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_VERActionPerformed
        // TODO add your handling code here:
                       try {
    String sql = ("SELECT FROM mascota WHERE mascota=?");
          con= DriverManager.getConnection("jdbc:mysql://localhost:3306/mascota","colunge","12345678");
          pst = con.prepareStatement(sql);
          pst.setString(1,jTextMASCOTA.getText());
          pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "Se mostro perfectamente. ");     
} 
catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo incertar los datos. Puede ser que el ID ya exista. Intenta mas tarde."); 
        }
           mostrarDatos();
    }//GEN-LAST:event_BOTON_VERActionPerformed

    private void BOTON_BORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_BORRARActionPerformed
        // TODO add your handling code here:
               try {
    String sql = ("DELETE FROM mascota WHERE mascota=?");
          con= DriverManager.getConnection("jdbc:mysql://localhost:3306/mascota","colunge","12345678");
          pst = con.prepareStatement(sql);
          pst.setString(1,jTextMASCOTA.getText());
          pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "Se registro perfectamente. Oprime ATRAS.");     
} 
catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo incertar los datos. Puede ser que el ID ya exista. Intenta mas tarde.");
//            e.printStackTrace();//imprimir excepciones de java  
        }
               mostrarDatos();
    }//GEN-LAST:event_BOTON_BORRARActionPerformed

    private void BOTON_MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_MODIFICARActionPerformed
                                         
       try {
    String sql = ("UPDATE mascota SET (mascota=?, raza=?, edad=?, dueño=?, celular=?)WHERE mascota=?");
          con= DriverManager.getConnection("jdbc:mysql://localhost:3306/mascota","colunge","12345678");
          pst = con.prepareStatement(sql);
          pst.setString(1,jTextMASCOTA.getText());
          pst.setString(2,jTextRAZA.getText());
          pst.setString(3,jTextEDAD.getText());
          pst.setString(4,jTextDUEÑO.getText());
          pst.setString(5,jTextCELULAR.getText());
          pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "Se MODIFICO perfectamente.");     
} 
catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo incertar los datos. Puede ser que el ID ya exista. Intenta mas tarde.");
//            e.printStackTrace();//imprimir excepciones de java  
        }
     mostrarDatos();
    }//GEN-LAST:event_BOTON_MODIFICARActionPerformed
       public void mostrarDatos(){
           try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mascota","colunge","12345678");
                String sql = ("SELECT FROM mascota");
                pst = con.prepareStatement(sql);
                rs=pst.executeQuery();
                tablamascotas.setModel(DbUtils.resultSetToTableModel(rs));   
           }
           catch (SQLException e) {
               
           }
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INICIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton BOTON_BORRAR;
    public javax.swing.JToggleButton BOTON_GUARDAR;
    private javax.swing.JToggleButton BOTON_MODIFICAR;
    public javax.swing.JToggleButton BOTON_VER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextCELULAR;
    public javax.swing.JTextField jTextDUEÑO;
    public javax.swing.JTextField jTextEDAD;
    private javax.swing.JTextField jTextMASCOTA;
    public javax.swing.JTextField jTextRAZA;
    private javax.swing.JTable tablamascotas;
    // End of variables declaration//GEN-END:variables
}
